[profile.default]
solc_version = '0.8.20'
src = "src"
out = "out"
libs = ["lib"]
remappings = ['solady/=lib/solady/src/', 'sol-json/=lib/sol-json/src/']
evm_version = 'shanghai'
cbor_metdata = false
ipfs_hash = 'none'

[rpc_endpoints]
mainnet = '${ETH_RPC_URL}'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
